# Generated by Django 4.2.2 on 2023-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=200)),
                ('key_text', models.CharField(max_length=200)),
                ('descriptions_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repositories_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
                ('update_text', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
